### ISSUE TITLE
How to use or start this repo??

### ISSUE THREAD

**Issue by Ai-is-light** [rienheuver/face-antispoofing-LBP#1]
Hi, I'm interested in face anti-spoofing tech, and I find your repo referenced many papers. However, I just not know how to use or start your repo

**Comment by rienheuver** [comment]
Hey man, as you can see this project hasn't been updated in 3 years. The readme might provide some small instructions on how to get it working, but other than that it's down to experimenting and debugging I'm afraid. Would be nice if you can make it work though :). Feel free to submit a pull request for the readme if you can get it working, so others might profit from it too.
